{% set name = "SimpleElastix" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SuperElastix/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 42f126b41d70ddf09cfd9f54a559c360eb78b769000be795684743efef39b7ff

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make     # [unix]
  host:
    - python
    - cmake
    - libtiff  # [unix]
    - libpng   # [unix]
    - jpeg     # [unix]
    - zlib     # [unix]
    - setuptools
  run:
    - python
    - libtiff  # [unix]
    - libpng   # [unix]
    - jpeg     # [unix]
    - zlib     # [unix]

test:
  imports:
    - SimpleITK

about:
  home: http://simpleelastix.github.io/
  license: Apache 2.0
  summary: User-friendly medical image registration library

extra:
  recipe-maintainers:
    - kaspermarstal
    - almarklein
